<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktív',
    'Are you sure you want to delete this user?' => 'Biztosan töröld ezt a felhasználót?',
    'Banned' => 'Tiltott',
    'Bind to IP' => 'IP-re korlátoz',
    'Browser' => 'Böngésző',
    'Change own password' => 'Saját jelszó cseréje',
    'Change password' => 'Jelszó cseréje',
    'Changing password' => 'Jelszó csere',
    'Changing password for user: ' => 'Jelszó cseréje a felhasználónál',
    'Child permissions' => 'Gyermek jogok',
    'Child roles' => 'Gyermek szerepek',
    'Code' => 'Kód',
    'Create' => 'Létrehoz',
    'Created' => 'Létrehozva',
    'Creating permission group' => '',
    'Current password' => 'Jelenlegi jelszó',
    'Data' => 'Adat',
    'Delete' => 'Törlés',
    'Description' => 'Leírás',
    'E-mail confirmed' => 'E-mail ellenőrizve',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => '',
    'Edit' => 'Szerkeszt',
    'Editing' => 'Szerkesztés',
    'Editing permission group' => 'Jogosultság csoport szerkesztése',
    'Editing permission: ' => 'Jogosultság szerkesztése',
    'Editing role: ' => 'Szerep szerkesztése',
    'Editing user: ' => 'Felhasználó szerkesztése',
    'For example: 123.34.56.78, 168.111.192.12' => 'Például: 123.34.56.78, 168.111.192.12',
    'Group' => 'Csoport',
    'Inactive' => 'Inaktív',
    'Language' => 'Nyelv',
    'Login' => 'Felh.',
    'Name' => 'Név',
    'OS' => 'Operációs rendszer',
    'Password' => 'Jelszó',
    'Password has been changed' => 'A jelszó cserélve',
    'Permission creation' => 'Jogosultság létrehozása',
    'Permission groups' => 'Jogosultság csoportok',
    'Permissions' => 'Jogosultságok',
    'Permissions for role - "{role}"' => 'Jogosultságok a "{role}" pozíciónak',
    'Permissions for role:' => 'Jogosultságok a pozíciónak:',
    'Registration IP' => 'Regisztrált IP',
    'Repeat password' => 'Jelszó mégegyszer',
    'Reset' => 'Visszaálit',
    'Role creation' => 'Pozíció létrehozása',
    'Roles' => 'Pozíciók',
    'Roles and permissions' => 'Pozíciók és jogosultságok',
    'Roles and permissions for user:' => 'Pozíciók és jogosultságok neki:',
    'Rule' => 'Szabály',
    'Save' => 'Mentés',
    'Saved' => 'Sikeres mentés',
    'Search' => 'Keresés',
    'Settings for permission' => 'A jogosultság beállításai',
    'Status' => 'Állapot',
    'Superadmin' => 'SuperAdmin',
    'Too many attempts' => 'Túl sok próbákozás',
    'Type' => 'Típus',
    'Updated' => 'Frissítve',
    'User' => 'Felhasználó',
    'User agent' => 'Felh. agent:',
    'User creation' => 'Felhasználó létrehozása',
    'Users' => 'Felhasználók',
    'Visit Time' => 'Látogatás ideje',
    'Visit log' => 'Látogatás részlete',
    'Wrong format. Enter valid IPs separated by comma' => 'Hibás formátum, írjon helyes IP címeket vesszövel elválasztva',
    'Wrong password' => 'Hibás jelszó',
    'You can not change own permissions' => 'Nem állíthatod át a saját jogaidat',
];
